from typing import Any

class TensorParallelApplicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def apply(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_to_model(self, *args: Any, **kwargs: Any) -> Any: ...
