from typing import Any

def init_distributed_environment(*args: Any, **kwargs: Any) -> None: ...
def initialize_model_parallel(*args: Any, **kwargs: Any) -> None: ...
def get_sequence_parallel_rank(*args: Any, **kwargs: Any) -> int: ...
def get_sequence_parallel_world_size(*args: Any, **kwargs: Any) -> int: ...
def get_sp_group(*args: Any, **kwargs: Any) -> Any: ...
def get_world_group(*args: Any, **kwargs: Any) -> Any: ...
