from typing import Any

def get_tensor_model_parallel_rank(*args: Any, **kwargs: Any) -> int: ...
def get_tensor_model_parallel_world_size(*args: Any, **kwargs: Any) -> int: ...
def get_sequence_parallel_world_size(*args: Any, **kwargs: Any) -> int: ...
def get_sequence_parallel_rank(*args: Any, **kwargs: Any) -> int: ...
def get_sp_group(*args: Any, **kwargs: Any) -> Any: ...
