flow:
  target: videotuna.flow.diffusers_video.DiffusersVideoFlow
  params:
    model_family: cogvideox
    mode: i2v
    pipeline_only: true
    model_variant: "1.5-i2v"
    pretrained_model_name_or_path: THUDM/CogVideoX1.5-5B-I2V
inference:
  mode: i2v
  ckpt_path: THUDM/CogVideoX1.5-5B-I2V
  savedir: results/i2v/cogvideox1.5-5b-i2v
  prompt_dir: inputs/i2v/576x1024
  frames: 81
  height: 768
  width: 1360
  num_inference_steps: 50
  unconditional_guidance_scale: 6.0
  seed: 42
  savefps: 16
  enable_model_cpu_offload: true
  enable_vae_tiling: true
  dtype: bf16
