flow:
  target: videotuna.flow.diffusers_video.DiffusersVideoFlow
  params:
    model_family: cogvideox
    mode: t2v
    pipeline_only: true
    pretrained_model_name_or_path: THUDM/CogVideoX-2b
    model_variant: "2b"
inference:
  mode: t2v
  ckpt_path: THUDM/CogVideoX-2b
  savedir: results/t2v/cogvideox-2b
  prompt_file: inputs/t2v/prompts.txt
  frames: 49
  height: 480
  width: 720
  num_inference_steps: 50
  unconditional_guidance_scale: 6.0
  seed: 42
  savefps: 8
