flow:
  target: videotuna.flow.diffusers_video.DiffusersVideoFlow
  params:
    model_family: mochi
    mode: t2v
    pipeline_only: true
    pretrained_model_name_or_path: genmo/mochi-1-preview
inference:
  mode: t2v
  ckpt_path: genmo/mochi-1-preview
  savedir: results/t2v/mochi
  prompt_file: inputs/t2v/prompts.txt
  frames: 84
  height: 480
  width: 848
  num_inference_steps: 50
  unconditional_guidance_scale: 4.5
  seed: 123
  savefps: 30
  enable_model_cpu_offload: true
  enable_vae_tiling: true
