flow:
  target: videotuna.flow.wan2.2-native.WanVideoModelFlow
  params:
    task: "t2v-A14B" # The task to run (choices from WAN_CONFIGS.keys())
    ckpt_path: "checkpoints/wan/Wan2.2-T2V-A14B" # The path to the checkpoint directory.
    offload_model: true # Whether to offload the model to CPU after each model forward.
    ulysses_size: 1 # The size of the ulysses parallelism in DiT.
    ring_size: 1 # The size of the ring attention parallelism in DiT.
    t5_fsdp: false # Whether to use FSDP for T5.
    t5_cpu: false # Whether to place T5 model on CPU.
    dit_fsdp: false # Whether to use FSDP for DiT.
    use_prompt_extend: false # Whether to use prompt extend.
    prompt_extend_method: "local_qwen" # The prompt extend method to use (choices: dashscope, local_qwen)
    prompt_extend_model: null # The prompt extend model to use.
    prompt_extend_target_lang: "zh" # The target language of prompt extend (choices: zh, en)
    seed: 42

    scheduler_config: __is_first_stage__

    denoiser_config:
      target: videotuna.models.wan.wan.modules.model.WanModel
      use_from_pretrained: true
      params:
        pretrained_model_name_or_path: ${flow.params.ckpt_path}

    first_stage_config:
      target: videotuna.models.wan.wan.modules.vae.WanVAE_
      params:
        dim: 96
        z_dim: 16
        dim_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        attn_scales: []
        temperal_downsample: [false, true, true]
        dropout: 0.0

    cond_stage_config:
      target: videotuna.models.wan.wan.modules.t5.T5Encoder
      params:
        dim: 4096
        dim_attn: 4096
        dim_ffn: 10240
        num_heads: 64
        num_buckets: 32
        shared_pos: false
        dropout: 0.1
        vocab: 256384
        num_layers: 24

inference:
  mode: t2v
  ckpt_path: "checkpoints/wan/Wan2.2-T2V-A14B"
  savedir: results/t2v/wan2.2-native
  seed: 42
  height: 480
  width: 832
  image: null
  prompt_file: "Two anthropomorphic cats in comfy boxing gear and bright gloves fight intensely on a spotlighted stage."
  solver: "unipc"
  num_inference_steps: 50
  time_shift: 3.0
  unconditional_guidance_scale: 5.0
  frames: 81
  n_samples_prompt: 1
  bs: 1
  savefps: 30
  enable_model_cpu_offload: true

  mapping:
    inference.ckpt_path: flow.params.ckpt_path
    inference.seed: flow.params.seed
    inference.enable_model_cpu_offload: flow.params.offload_model
    inference.ulysses_degree: flow.params.ulysses_size
    inference.ring_degree: flow.params.ring_size
